/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BadgeText: typeof import('./components/general/text/BadgeText.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShortPresentation: typeof import('./components/about/ShortPresentation.vue')['default']
    TopNavbar: typeof import('./components/general/navbar/TopNavbar.vue')['default']
  }
}
